In [11]:
#for scan in file
# (scan) + (scan+1)
# for point in scan1
#  find nearest point in scan2
#  append point1 and nearest point to {}
#  add for each scan

In [12]:
from skimage.feature import peak_local_max
import csv
import importlib
import sys
import os
cur=os.getcwd()
paths = [cur := os.path.dirname(cur) for _ in range(3)]
sys.path.insert(0, paths[0])
from Helpers import loadData
importlib.reload(sys.modules['Helpers.loadData'])
importlib.reload(sys.modules['Helpers'])

importlib.reload(sys.modules['Helpers'])

<module 'Helpers' from 'd:\\temp1\\Granular-Compression\\Identification\\Helpers\\__init__.py'>

In [13]:
positions = [] 

with open('Cycle3s3peaks.csv', 'r', encoding='utf-8-sig') as csv_file:
    reader = csv.DictReader(csv_file)
    print(reader.fieldnames)
    row = list(reader)

    for i, r in enumerate(row):
      z = float(r['z'])
      y = float(r['y'])
      x = float(r['x'])
      positions.append((z,y,x))
      print(f'Particle{i+1}:', z, y, x)

    #print(positions[0]) for position 1
   
 

    #for row in reader:
        #print(row['positionx'], row['positiony'], row['positionz'])
    


['z', 'y', 'x']
Particle1: 497.0 761.0 829.0
Particle2: 693.0 71.0 729.0
Particle3: 599.0 67.0 315.0
Particle4: 638.0 127.0 762.0
Particle5: 540.0 69.0 686.0
Particle6: 493.0 76.0 774.0
Particle7: 569.0 96.0 791.0
Particle8: 298.0 774.0 504.0
Particle9: 394.0 762.0 670.0
Particle10: 585.0 766.0 791.0
Particle11: 240.0 756.0 766.0
Particle12: 329.0 759.0 607.0
Particle13: 445.0 766.0 579.0
Particle14: 555.0 116.0 588.0
Particle15: 377.0 760.0 503.0
Particle16: 688.0 64.0 130.0
Particle17: 605.0 59.0 144.0
Particle18: 561.0 85.0 52.0
Particle19: 354.0 731.0 70.0
Particle20: 514.0 155.0 782.0
Particle21: 518.0 757.0 731.0
Particle22: 420.0 152.0 60.0
Particle23: 510.0 62.0 322.0
Particle24: 658.0 739.0 828.0
Particle25: 636.0 123.0 584.0
Particle26: 206.0 773.0 186.0
Particle27: 517.0 67.0 515.0
Particle28: 321.0 761.0 156.0
Particle29: 397.0 701.0 588.0
Particle30: 626.0 41.0 777.0
Particle31: 446.0 126.0 817.0
Particle32: 461.0 69.0 52.0
Particle33: 588.0 183.0 804.0
Particle34: 578.0 1

In [14]:
positions1 = [] 

with open('Cycle4s3peaks.csv', 'r', encoding='utf-8-sig') as csv_file:
    reader = csv.DictReader(csv_file)
    print(reader.fieldnames)
    row = list(reader)

    for i, r in enumerate(row):
      z = float(r['z'])
      y = float(r['y'])
      x = float(r['x'])
      positions1.append((z,y,x))
      print(f'Particle{i+1}:', z, y, x)



['z', 'y', 'x']
Particle1: 634.0 164.0 775.0
Particle2: 712.0 53.0 794.0
Particle3: 686.0 93.0 138.0
Particle4: 489.0 105.0 783.0
Particle5: 559.0 31.0 355.0
Particle6: 580.0 220.0 809.0
Particle7: 678.0 229.0 815.0
Particle8: 597.0 95.0 326.0
Particle9: 505.0 596.0 825.0
Particle10: 512.0 33.0 641.0
Particle11: 685.0 110.0 729.0
Particle12: 726.0 177.0 755.0
Particle13: 556.0 141.0 601.0
Particle14: 593.0 35.0 659.0
Particle15: 606.0 89.0 141.0
Particle16: 512.0 184.0 778.0
Particle17: 395.0 733.0 591.0
Particle18: 559.0 115.0 55.0
Particle19: 390.0 793.0 666.0
Particle20: 584.0 795.0 787.0
Particle21: 533.0 99.0 694.0
Particle22: 572.0 172.0 705.0
Particle23: 241.0 787.0 761.0
Particle24: 517.0 30.0 447.0
Particle25: 354.0 761.0 69.0
Particle26: 669.0 51.0 68.0
Particle27: 296.0 804.0 499.0
Particle28: 348.0 722.0 683.0
Particle29: 425.0 183.0 66.0
Particle30: 317.0 737.0 241.0
Particle31: 443.0 162.0 829.0
Particle32: 461.0 102.0 56.0
Particle33: 510.0 92.0 330.0
Particle34: 740.0 7

In [15]:

print(positions1[684][0])
for i in enumerate(positions1):
    if positions1[0] == 85:
        print(pos)

85.0


In [16]:
# I want to sort list B and make it similar to List A
import numpy as np
from scipy.optimize import linear_sum_assignment
from scipy.spatial.distance import cdist

i = np.array(positions)
j = np.array(positions1)

part = cdist(i, j)
row_ind, col_ind = linear_sum_assignment(part)

for a, b in zip( row_ind, col_ind):
    print(positions[a],'<->', positions1[b],'dist:', part[a, b])

(497.0, 761.0, 829.0) <-> (455.0, 722.0, 830.0) dist: 57.323642591866054
(693.0, 71.0, 729.0) <-> (667.0, 34.0, 706.0) dist: 50.73460357586329
(599.0, 67.0, 315.0) <-> (636.0, 32.0, 356.0) dist: 65.3834841531101
(638.0, 127.0, 762.0) <-> (685.0, 110.0, 729.0) dist: 59.89156868875618
(540.0, 69.0, 686.0) <-> (533.0, 99.0, 694.0) dist: 31.827660925679098
(493.0, 76.0, 774.0) <-> (473.0, 35.0, 738.0) dist: 58.111960903070546
(569.0, 96.0, 791.0) <-> (554.0, 35.0, 756.0) dist: 71.90966555338719
(298.0, 774.0, 504.0) <-> (296.0, 804.0, 499.0) dist: 30.479501308256342
(394.0, 762.0, 670.0) <-> (390.0, 793.0, 666.0) dist: 31.51190251317746
(585.0, 766.0, 791.0) <-> (584.0, 795.0, 787.0) dist: 29.29163703175362
(240.0, 756.0, 766.0) <-> (241.0, 787.0, 761.0) dist: 31.416556144810016
(329.0, 759.0, 607.0) <-> (328.0, 790.0, 598.0) dist: 32.29551052391029
(445.0, 766.0, 579.0) <-> (445.0, 796.0, 575.0) dist: 30.265491900843113
(555.0, 116.0, 588.0) <-> (556.0, 141.0, 601.0) dist: 28.195744359743

In [ ]:
#compare both files
#make radius bubble 
#track particles


In [ ]:
 # Load convolution and raw data
path = r'D:\Users\Lab User\Desktop\temp1\Granular-Compression\Data'
conv = loadData(path,'fCycle2s3Conv.hdf5')
data = loadData(path,'fCycle2s3Raw.hdf5')


FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'C:\Users\Lab User\Desktop\temp1\Granular-Compression\Data\fCycle2s3Conv.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
# Find peaks from conv
peaks = peak_local_max(conv,min_distance=30) 

In [ ]:
print(peaks)

[[463  84 859]
 [653 147 859]
 [393 727 811]
 ...
 [129  81 192]
 [ 64  73 465]
 [119 134 128]]
